### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by lomagnin** [RWaltersMA/mongo-spark-jupyter#2]
Hi,
Does anyone know how to make the run.sh script compatible with Windows?
Thanks!

**Comment by RWaltersMA** [comment]
I just write a Powershell script called, "run.ps1" and checked it in.  That is equivalent to the run.sh.  Let me know if this works for you, thanks!

**Comment by lomagnin** [comment]
@RWaltersMA, according to my student who's on Windows, your script is working fine!
Thank you so much!
